services:
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_app_backend
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - "4001:4001"
    networks:
      - blog_app_network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog_app_frontend
    restart: always
    ports:
      - "5173:80"
    networks:
      - blog_app_network

networks:
  blog_app_network:
    driver: bridge
    name: blog_app_network
